djangoProjects/urls.py
from LaboSable import views as views_LabS
from Webfautheque import views
from django.contrib import admin
from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [

    # racine 
    re_path(r'^$',
            views.home,
            name=""),

    # ex: /LaboSable/
    re_path(r'^LaboSable/$',
            views_LabS.main,
            name="LaboSable"),

    # ex: /index/
    re_path(r'^home/$',
            views.home,
            name="home"),

    # ex: /Webfautheque/admin/
    path('admin/', admin.site.urls),

    # ex: /Webfautheque/Arborescence/
    re_path(r'^Webfautheque/Arborescence/$',
            views.page_arborescence_defautheque,
            name="page_arborescence_defautheque"),

    # ex: /Webfautheque/A/
    re_path(r'^Webfautheque/(?P<classe_idperso>[A-G])/$',
            views.page_groupes_defautheque,
            name="page_groupes_defautheque"),

    # ex: /Webfautheque/A100/
    re_path(r'^Webfautheque/(?P<classe_idperso>[A-G])(?P<groupe_idperso_one_char>[1-9])00/$',
            views.page_sous_groupes_defautheque,
            name="page_sous_groupes_defautheque"),

    # ex: /Webfautheque/A110/
    re_path(
        r'^Webfautheque/(?P<classe_idperso>[A-G])(?P<groupe_idperso_one_char>[1-9])(?P<sous_groupe_idperso_one_char>[1-9])0/$',
        views.page_defauts_defautheque,
        name="page_defauts_defautheque"),

    # ex: /Webfautheque/A111/
    re_path(r'^Webfautheque/(?P<defaut_idperso>[A-G][1-9]{3})/$',
            views.page_presentation_defaut,
            name="page_presentation_defaut"),

    # ex: /Webfautheque/A111/Experiences/
    re_path(r'^Webfautheque/(?P<defaut_idperso>[A-G][1-9]{3})/Experiences/$',
            views.page_choix_experience,
            name="page_choix_experience"),

    # ex: /Webfautheque/A111/Experiences/Consultation:1/
    re_path(r'^Webfautheque/(?P<defaut_idperso>[A-G][1-9]{3})/Experiences/Consultation:(?P<experience_id>[0-9]+)/$',
            views.page_consultation_experience,
            name="page_consultation_experience"),

    # ex: /Webfautheque/A111/Experiences/Ajout/
    re_path(r'^Webfautheque/(?P<defaut_idperso>[A-G][1-9]{3})/Experiences/Ajout/$',
            views.page_ajout_experience,
            name="page_ajout_experience"),

    # ex: /Webfautheque/Experiences/Ajout/
    re_path(r'^Webfautheque/Experiences/Ajout/$',
            views.page_ajout_experience,
            name="page_ajout_experience_defaut"),

        # ex: /Webfautheque/A111/Experiences/Update/
    re_path(r'^Webfautheque/(?P<id>[A-G][1-9]{3})/Experiences/Consultation:(?P<experience_id>[0-9]+)/Update/$',
            views.page_update_experience,
            name="page_update_experience"),

        # ex: /Webfautheque/A111/Experiences/Delete/
        re_path(r'^Webfautheque/(?P<id>[A-G][1-9]{3})/Experiences/Consultation:(?P<experience_id>[0-9]+)/Delete/$',
                views.page_delete_experience,
                name="page_delete_experience"),

    # ex: /Webfautheque/experiences/
        re_path(r'^Webfautheque/experiences', 
                views.experience_list,
                name="experience_list"),
    # ex: /Webfautheque/login/
        re_path(r'login/', 
                views.login_user,
                name="login_user"),
    # ex: /Webfautheque/logout/
        re_path(r'logout/', 
                views.logout_user,
                name="logout_user"),
    # ex: /Webfautheque/experiences/search-experiences/
        re_path(r'experiences/search_experiences', 
                csrf_exempt(views.search_experiences),
                name="search_experiences"),

    # filtre de recherche
        re_path(r'experiences/(?P<defaut_idperso>[A-G][1-9]{3})/search_experiences_by_defaut', 
                csrf_exempt(views.search_experiences_by_defaut),
                name="search_experiences_by_defaut"),

    # filtre de recherche
        re_path(r'experiences/experienceByAuteur', 
                csrf_exempt(views.experienceByAuteur),
                name="experienceByAuteur"),

    # filtre de recherche
        re_path(r'experiences/(?P<defaut_idperso>[A-G][1-9]{3})/experienceAuteurDefaut', 
                csrf_exempt(views.experienceAuteurDefaut),
                name="experienceAuteurDefaut"),                

    # filtre de recherche
        re_path(r'experiences/experienceByDefaut', 
                csrf_exempt(views.experienceByDefaut),
                name="experienceByDefaut"),     
        
    # ex: /Webfautheque/liste_defauts/
        re_path(r'^Webfautheque/liste_defauts', 
                views.pages_defauts_liste,
                name="liste_defauts"),
]

Webfautheque/models.py
import os

from django.db import models
from django.dispatch import receiver
from django.utils import timezone


class Classe(models.Model):
    """
    Cette classe regroupe le plus haut niveau d' arborescence de la défauthèque
    à savoir les 7 Classes de bases : A, B, C, D, E, F, G
    """
    classe_idperso = models.CharField('Classe', max_length=1)
    classe_nom = models.CharField('Intitulé', max_length=2000)

    def __str__(self):
        return self.classe_idperso


class Groupe(models.Model):
    """Cette classe regroupe le niveau d' arborescence juste en dessous de la classe Classe,
    il corresponds aux groupes de défauts : A100, A200, C100 etc...
    Elle est liée à la classe Classe
    """

    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    groupe_idperso = models.CharField('Nom du groupe', max_length=4)
    groupe_nom = models.CharField('Description ', max_length=2000)

    def __str__(self):
        return self.groupe_idperso

    # affiche l'intitulé de la classe
    def nom_classe(self):
        return self.classe.classe_idperso


class Sous_groupe(models.Model):
    """Cette classe regroupe le niveau d' arborescence juste en dessous des Groupe,
    il correspond aux sous-groupes de défaut :  A110, A120, C130 etc ...
    Elle est liée à la classe Groupe
    """

    groupe = models.ForeignKey('Groupe', on_delete=models.CASCADE)
    sous_groupe_idperso = models.CharField('Sous groupe', max_length=4)
    sous_groupe_nom = models.CharField('Description', max_length=2000)

    def __str__(self):
        return self.sous_groupe_idperso

    # affiche l'intitulé du groupe
    def nom_groupe(self):
        return self.groupe.groupe_idperso


class Defaut(models.Model):
    """
    Cette classe regroupe le dernier niveau d' arborescence de la défauthèque,
    il s' agit des défauts : A111, A123, C131 etc...
    Elle référence toutes les informations générales à savoir sur un défaut (nom, description, info, causes, remèdes)
    Elle est liée à la classe sous_groupe
    """
    sous_groupe = models.ForeignKey(Sous_groupe, on_delete=models.CASCADE)
    defaut_idperso = models.CharField('Code defaut', max_length=4)
    defaut_nom = models.CharField('Nom defaut', max_length=2000)
    defaut_image = models.ImageField('Image', upload_to='static/Webfautheque/presentation_defauts',
                                     default="None", blank=True)
    defaut_description = models.TextField('Description', max_length=20000)
    defaut_info = models.TextField('Information', max_length=20000)
    defaut_causes = models.TextField('Causes', max_length=20000)
    defaut_remedes = models.TextField('Remedes', max_length=20000)
    defaut_modif_date = models.DateTimeField('Date de modification', default=None, blank=True)
    
    def __str__(self):
        return self.defaut_idperso

    # affiche l'intitulé du sous groupe
    def _sous_groupe(self):
        return self.sous_groupe.sous_groupe_idperso

    def save(self, *args, **kwargs):
        self.defaut_modif_date = timezone.now()
        if self.defaut_image:
            self.defaut_image.name = self.defaut_idperso+ '/' + self.defaut_image.name
        super(Defaut, self).save(*args, **kwargs)
    


@receiver(models.signals.post_delete, sender=Defaut)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    '''
    Supprime les images de l'experience
    '''
    if instance.defaut_image:
        if os.path.isfile(instance.defaut_image.path):
            os.remove(instance.defaut_image.path)


@receiver(models.signals.pre_save, sender=Defaut)
def auto_delete_file_on_change(sender, instance, **kwargs): 
    '''
    Supprime les images de l'experience
    '''
    if not instance.pk:
        return False
    try:
        old_file = Defaut.objects.get(pk=instance.pk).defaut_image
    except Defaut.DoesNotExist:
        return False
    new_file = instance.defaut_image
    if not old_file == new_file:
        if(old_file):
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)
            else:
                return False
        else:
            return False


class Experience(models.Model):
    """
    Cette classe est lié à un défaut (class Defaut), elle représente une experience de l' utilisateur.
    """
    experience_nom_article = models.CharField(
        'numéro article', max_length=2000)
    defaut = models.ForeignKey(Defaut,
                               on_delete=models.CASCADE)
    experience_auteur = models.CharField(
        'Auteur', max_length=2000, blank=True,  null=True)
    experience_pub_date = models.DateTimeField('date', default=timezone.now)
    experience_rapport_anomalie = models.CharField(
        'Rapport anomalie', max_length=2000, default="None", blank=True)
    experience_ift = models.CharField(
        'Ift', max_length=2000, default="None", blank=True)
    experience_photos_1 = models.ImageField(
        'Photo 1', upload_to='static/Webfautheque/photos', default="None")
    experience_photos_2 = models.ImageField(
        'Photo 2', upload_to='static/Webfautheque/photos', default="None")
    experience_descriptif = models.TextField(
        'descriptif', max_length=50000, default=" ")
    experience_remedes = models.TextField(
        'remedes', max_length=20000, default="")
    experience_document = models.FileField(
        'Document', upload_to='static/Webfautheque/documents', default="None")
    defaut = models.ManyToManyField(Defaut, blank=False)
    experience_chemin_ift = models.CharField('chemin_ift', max_length=2000, default="",blank=True)
    experience_chemin_rapport = models.CharField('chemin_rapport', max_length=2000, default="", blank=True)

    # affichage intitulé du défaut
    def nom_defaut(self):
        return self.defaut.defaut_nom

    # cas URL sur le reseau / changer le model en CharField / supprimer la condition du rapport dans auto_delete
    def save(self, *args, **kwargs):
        super(Experience, self).save(*args, **kwargs)
        if self.experience_chemin_rapport:
            self.experience_chemin_rapport = self.experience_chemin_ift.replace("\\", "/")
            if self.experience_chemin_ift[:10] == "//FERRY10/" :
                self.experience_chemin_ift = self.experience_chemin_ift[10:]
        if self.experience_chemin_ift:
            self.experience_chemin_ift = self.experience_chemin_ift.replace("\\", "/")
            if self.experience_chemin_ift[:14] == "//FERRY04/ift/" :
                self.experience_chemin_ift = self.experience_chemin_ift[14:]

        return super(Experience, self).save(*args, **kwargs)


@receiver(models.signals.post_delete, sender=Experience)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    '''
    Supprime les images/fichiers de l'experience
    '''
    if instance.experience_photos_1:
        if os.path.isfile(instance.experience_photos_1.path):
            os.remove(instance.experience_photos_1.path)
    if instance.experience_photos_2:
        if os.path.isfile(instance.experience_photos_2.path):
            os.remove(instance.experience_photos_2.path)


@receiver(models.signals.pre_save, sender=Experience)
def auto_delete_file_on_change(sender, instance, **kwargs):
    '''
    Remplace les images/fichiers si suppression
    '''
    if not instance.pk:
        return False
    try:
        old_file= Experience.objects.get(pk=instance.pk).experience_ift
    except Experience.DoesNotExist:
        return False
    
    if not old_file == instance.experience_photos_1:
        if os.path.isfile(old_file):
            os.remove(old_file.path)
    if not old_file == instance.experience_photos_2:
        if os.path.isfile(old_file):
            os.remove(old_file.path)

templates/Webfautheque/arborescence.html
<!DOCTYPE html>
<html lang="fr">

{% extends "Webfautheque/base.html" %}
{% load static %}

{% block title %}
WikiFC - Arborescence
{% endblock %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/classe_groupe.css' %}"/>

    <a href="/Webfautheque/liste_defauts" class="connection">Accès à la liste des defauts </a>

    <div class="list_classe">
        <ul>
            {% for classe in classes_list %}
            <li><a href="/Webfautheque/{{ classe.classe_idperso }}">Classe {{ classe.classe_idperso }}
                : {{ classe.classe_nom }}</a></li>
        {% endfor %}
    </ul>
    <ul>
        {% for def in defaut_image %}
            <li>{{ def.defaut_idperso }} </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

templates/Webfautheque/base.html
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta description="Defautheque" />
{% load static %}

<html lang="fr">
  <head>
    <title>{% block title %} WIKI - FC{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
  </head>

  <body>
    {% include "Webfautheque/header.html" %} {% block content %} {% endblock %}
    {% include "Webfautheque/footer.html" %}
  </body>
</html>

templates/Webfautheque/consultation_experience.html
<!DOCTYPE html>
<html lang="fr">

  {% extends "Webfautheque/base.html" %} 
  {% load static %} {% get_static_prefix as STATIC_PREFIX %}
  {% block title %} WikiFC - Expérience {{experience.experience_nom_article }}
  {% endblock %} 

  {% block content %}
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/consultation_experience.css' %}"
  />
  </script>

  {% comment %} variable url, prends de façon dynamique l'url de l'appli {% endcomment %}
  {% with 'http://'|add:request.META.HTTP_HOST|add:'/Webfautheque/experiences' as  url %}
  {% with 'http://'|add:request.META.HTTP_HOST|add:'/Webfautheque/'|add:defaut_idperso|add:'/' as defautUrl %}

  {% if request.META.HTTP_REFERER ==  url  %}
    <a href="/Webfautheque/experiences" class="btn-retour">Expériences </a>
  {% elif request.META.HTTP_REFERER == defautUrl %}
    <a href="/Webfautheque/{{defaut_idperso}}" class="btn-retour">Défaut </a>
  {% else %}  
    <a href="/Webfautheque/{{ defaut_idperso }}/Experiences" class="btn-retour">Expériences </a>
  {% endif %}
  {% endwith %}
  {% endwith %}
  <div class="content">
    <div class="title_button">
      <div class="title">
        <h1>
         Experience {{ experience.experience_nom_article}}.
        </h1>
        <p>Defaut : {{ defaut_idperso }}</p>
      </div>
      <div class="update_form"></div>
    </div>

    <div class="experience_content">
      <div class="experience_content_left">
        <div class="experience_illustration">
          <h2></h2>
          {% load static %} {% get_static_prefix as STATIC_PREFIX %}
          <img class="illustration"
            src="/{{ defaut_image }}"
            alt="Illustration schématique du défaut"
            />
        </div>
        <div class="experience_description">
          <h2 class="titres">Description</h2>
          <p>{% for desc in descriptif %} {{ desc }} {% endfor %}</p>
        </div>
        <div class="experience_remede">
          <h2 class="titres">Remède</h2>
          <p>{% for rem in remedes %} {{ rem }} {% endfor %}</p>
        </div>

        <div class="experiences_images">
          <div class="rapport_anomalie">
            <h2 class="titres">Rapport d'anomalie</h2>
            {% if experience.experience_chemin_rapport != 'None' %}
              <a href="{% static 'ferry10/' %}{{experience.experience_chemin_rapport}} ">
              Afficher le rapport d'anomalie</a>
            {% else %}
            <p>Aucun rapport d'anomalie</p>
            {% endif %}
          </div>
        </div>

        <div class="experience_document">
          <h2 class="titres">Document</h2>
          {% if experience.experience_document != 'None' %}
            <a href="/{{ experience.experience_document }}">
            Afficher le document</a>
          {% else %}
          <p>Aucun document</p>
          {% endif %}
          </div>

      </div>
      <div class="experience_content_right">
        <div class="image_ift">
          <h2 class="titres">IFT</h2>
          {% if experience.experience_chemin_ift != 'None' %}
          <a href="{% static 'ift/' %}{{experience.experience_chemin_ift}} ">
            Afficher IFT</a>
          {% else %}
          <p>Aucun IFT disponible</p>

          {% endif %} 
        </div>

        <div class="photo">
          <h2 class="titres">Photo</h2>
          {% if experience.experience_photos_1 != 'None' %}
          <a href="/{{ experience.experience_photos_1 }}"><img src="/{{ experience.experience_photos_1 }}" alt="image IFT" /></a>
          {% else %}
          {% endif %}

          {% if experience.experience_photos_2 != 'None' %}
          <a href="/{{ experience.experience_photos_2 }}"><img src="/{{ experience.experience_photos_2 }}" alt="image IFT" /></a>
          {% else %}
          {% endif %}
        </div>
      </div>
    </div>

    <div class="experience_date">
      <p>Publié le {{ experience.experience_pub_date }} par </p>
      <p class="auteur_uppercase"> &#8205;  {{experience.experience_auteur}}</p>
    </div>
  </div>

  {% endblock %}

</html>

templates/Webfautheque/description_defaut.html
<!DOCTYPE html>
<html lang="fr">
{% extends "Webfautheque/base.html" %} {% load static %} {% block title %}
WikiFC - Défaut {{ defauts_carac.defaut_idperso }} {% endblock %} {% block content %}


<link rel="stylesheet" type="text/css" href="{% static 'css/description_defaut.css' %}" />
<div class="content">
  <a  class="btn-retour" href="/Webfautheque/{{ defaut_sous_groupe }}/"> Retour</a>

  <div class="contenu">
    <div class="titre">
      <h1>{{ defaut_idperso }}: {{ defaut_nom }}</h1>
    </div>
  </div>


  <div class="top_content">
    <div class="top_content_left">
      <div class="top_content_left_image">
       {% load static %} {% get_static_prefix as STATIC_PREFIX %}
       
        <img src="/{{ defaut_image }}"
          alt="Illustration schématique du défaut" />
      </div>
    </div>
    <div class="top_content_right">
      <div class="top_content_right_texte">
        <p>
          <h2>Description</h2>
        </p>
        <p>
          {{ defaut_description }}
        </p>
      </div>
      <div class="defaut_info">
        <h2>Informations</h2>
        <p>{% for info in defaut_infos %} {{ info }}</p>

        <p>{% endfor %}</p>
      </div>
    </div>
  </div>


  <div class="bottom_content">
    <div class="bottom_content_left">
      <div class="bottom_content_left_texte">
        <h2> Causes </h2>
        <p>
          {% for cause in defaut_causes %} {{ cause }}</p> {% endfor %}
        </p>
      </div>
    </div>
    <div class="bottom_content_right">
      <div class="bottom_content_right_texte">
        <h2> Remèdes </h2>
        <p>
          {% for remede in defaut_remedes %} {{ remede }} </p>{% endfor %}
        </p>
      </div>
    </div>
</div>


<div class="footer_content">
  <div class="footer_content_texte">
    <h2>Expériences</h2>   
    <p>
      <a href="/Webfautheque/{{ defaut_idperso }}/Experiences">Lien vers les expériences enregistrées pour ce défaut</a>
        <ul>
      {% for exp in experience_list %}<li> <a class="liste_experiences" href="/Webfautheque/{{ defaut_idperso }}/Experiences/Consultation:{{ exp.id }}">{{ exp.experience_nom_article }}</a> </li>{% endfor %}
        </ul>
  </div>
  <div class="footer_content_right">
    {% with defaut_modif_date as date  %}
    <p>{% endwith %}
    {% if defaut_modif_date == NULL  %}
        {% else %}
          <p> Modifié le {{ defaut_modif_date }} </p>
    {% endif %}
</div>


{% endblock %}
</html>

templates/Webfautheque/experience_ajout.html
<!DOCTYPE html>
<html lang="fr">
  <meta charset="utf-8">  
  {% extends "Webfautheque/base.html" %} {% load static %} {% block title %}

  WikiFC - Ajout expérience {% endblock %} {% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/experience_form.css' %}" />

  <div class='content_list'>
    <h1 class='title_experience'>Création d'une expérience {{nom_defaut}}</h1>

  <form enctype="multipart/form-data" method="POST" class="experience-form">
    {% csrf_token %}
    <div class="add_form_content">
      <div class="form-group">
        <input type="date" class="form-control" id="experience_pub_date" name="experience_pub_date" value="2018-07-22" hidden>
      </div>

      <div class="form_content">
        <div class='form_text'>
          <p> Numéro d'article : 
        </div>
        <div class="form_input">
          <label for="id_experience_nom_article"></label>
          {{ experience_form.experience_nom_article}}
        </div>
      </div>
      <div class="form_content">
        <div class='form_text'>
          <p> Defaut :
        </div>

        <div class='form_input'>

          {% comment %} <div class="multiselect">
            <div class="selectBox" onclick="showCheckboxes()">
              <select name="defaut" id="id_defaut" class="form-control">
                {% if nom_defaut is null %}
                <option value="" selected disabled hidden>Choisissez un defaut</option>
                <option value="{{defaut_id}}" required hidden>{{nom_defaut}} </option>
              {% endif %}
              {% for list in liste_defaut %}
              <option value="{{list.id}}">{{list.defaut_nom }}</option>
              {% endfor %}
              </select>
              <div class="overSelect"></div>
            </div>
            <div id="checkboxes">
              {% for list in liste_defaut %}

              <label for="{{list.id}}">
                <input type="checkbox" id="{{list.id}}" />{{list.defaut_nom }}</label>
                {% endfor %}
            </div>
          </div> {% endcomment %}

          
          <select name="defaut" id="id_defaut" class="form-control">
            
            {% if nom_defaut is null %}
              <option value="" selected disabled hidden>Choisissez un defaut</option>
            {% else %}
            <option value="{{defaut_id}}" required hidden>{{nom_defaut}} </option>
            {% endif %}

            {% for list in liste_defaut %}
            <option value="{{list.id}}">{{list.defaut_nom }}</option>
            {% endfor %}
          </select> 


          
        </div>
      </div>



    
    <div class="form_content">

      <div class="form_input">
        <label for="id_experience_auteur"></label>
        {{ experience_form.experience_auteur}}
      </div>
    </div>
    <div class="form_content">
      <div class='form_text'>
        <p> chemin d'acces rapport anomalie :
      </div>
      <div class="form_input">
        <label for="experience_chemin_rapport"></label>
        {{ experience_form.experience_chemin_rapport }}
      </div>
    </div>
    <div class="form_content">
      <div class='form_text'>
        <p> chemin d'acces IFT :
      </div>
      <div class="form_input">
        <label for="experience_chemin_ift"></label>
        {{ experience_form.experience_chemin_ift }}
      </div>
    </div>
    <div class="form_content">
      <div class='form_text'>
        <p> Photo 1:
      </div>
      <div class="form_input">
        {{ experience_form.experience_photos_1}}
      </div>
    </div>
    <div class="form_content">
      <div class='form_text'>
        <p> Photo 2 :
      </div>
      <div class="form_input">
        {{ experience_form.experience_photos_2}}
      </div>
    </div>
    <div class="form_content">
      <div class='form_text'>
        <p> Document:
      </div>
      <div class="form_input">
        {{ experience_form.experience_document}}
      </div>
    </div>
    <div class="form_content">
      <div class='form_text'>
        <p> Descriptif :   
      </div>
      <div class="form_input">
        {{ experience_form.experience_descriptif}}
      </div>
    </div>
      <div class="form_content">
      <div class='form_text'>
        <p> Remedes :  
      </div>
      <div class="form_input">
        {{ experience_form.experience_remedes}}
      </div>
    </div>

    <div class="form_button"> 
      <button class="btn_cancel"> <a href= "/Webfautheque/experiences/" class="btn btn-primary">Retour</a> </button>
      <button type="submit" class="btn_ajout">Enregistrer</button>
    </div>
  </form>

</div>
<script>
  var expanded = false;

  function showCheckboxes() {
    var checkboxes = document.getElementById("checkboxes");
    if (!expanded) {
      checkboxes.style.display = "block";
      expanded = true;
    } else {
      checkboxes.style.display = "none";
      expanded = false;
    }
  }
  </script>
  
  {% endblock %}

</html>

templates/Webfautheque/experience_update.html
<!DOCTYPE html>
<html lang="fr">
  {% extends "Webfautheque/base.html" %} {% load static %} {% block title %}
  WikiFC - Modification de l'expérience {% endblock %} {% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/experience_form.css' %}" />


  <div class='content_list'>
    <h1 class='title_experience'>Modification de l'expérience {{nom_exp}} </h1>

    <form enctype="multipart/form-data" method="POST" class="experience-form">
      {% csrf_token %}
      <div class="add_form_content">
        <div class="form-group">
          <input type="date" class="form-control" id="experience_pub_date" name="experience_pub_date" value="2018-07-22" hidden>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="experience_auteur" name="experience_auteur" value={{user}} hidden>
        </div>



        <div class="form_content">
          <div class='form_text'>
            <p> Numéro d'article : 
          </div>
          <div class="form_input">
            {{ experience_form.experience_nom_article}}
          </div>
        </div>


        <div class="form_content">
          <div class='form_text'>
            <p> Defaut :
          </div>

          <div class='form_input'>
            <select name="defaut" id="id_defaut" class="form-control">
              <option value="{{defaut_id}}" required hidden>{{nom_defaut}} </option>
              {% for list in liste_defaut %}

                <option value="{{list.id}}">{{list.defaut_nom }}</option>

              {% endfor %}
              
            </select>
          </div>
        </div>

    
        <div class="form_content">
          <div class='form_text'>
            <p> Rapport anomalie :
          </div>
          <div class="form_input">
            {{ experience_form.experience_rapport_anomalie }}
          </div>
        </div>
        <div class="form_content">
          <div class='form_text'>
            <p> chemin d'acces rapport anomalie :
          </div>
          <div class="form_input">
            <label for="experience_chemin_rapport"></label>
            {{ experience_form.experience_chemin_rapport }}
          </div>
        </div>
          <div class="form_content">
          <div class='form_text'>
            <p> Ift : 
          </div>
          <div class="form_input">
            {{ experience_form.experience_ift }}
          </div>
        </div>
        <div class="form_content">
          <div class='form_text'>
            <p> chemin d'acces IFT :
          </div>
          <div class="form_input">
            <label for="experience_chemin_ift"></label>
            {{ experience_form.experience_chemin_ift }}
          </div>
        </div>


        <div class="form_content">
        <div class='form_text'>
          <p> Photo 1:
        </div>
        <div class="form_input">
          {{ experience_form.experience_photos_1}}
        </div>
      </div>
      <div class="form_content">
        <div class='form_text'>
          <p> Photo 2 :
        </div>
        <div class="form_input">
          {{ experience_form.experience_photos_2}}
        </div>
      </div>
      <div class="form_content">
        <div class='form_text'>
          <p> Document:
        </div>
        <div class="form_input">
          {{ experience_form.experience_document}}
        </div>
      </div>
      <div class="form_content">
        <div class='form_text'>
          <p> Descriptif :   
        </div>
        <div class="form_input">
          {{ experience_form.experience_descriptif}}
        </div>
      </div>
        <div class="form_content">
        <div class='form_text'>
          <p> Remedes :  
        </div>
        <div class="form_input">
          {{ experience_form.experience_remedes}}
        </div>
      </div>

      <div class="form_button"> 
        <button class="btn_cancel"> <a href= "/Webfautheque/experiences/" class="btn btn-primary">Retour</a> </button>
        <button type="submit" class="btn_ajout">Modifier</button>
      </div>
    </form>

  </div>
    {% endblock %}
</html>